version: '3.3'

services:
  entry_db:
    image: entry_db
    restart: always
    ports:
      - "3306:3306"
    hostname: entry_db
    networks:
      - grades_app
  
  entry:
    image: entry
    restart: always
    ports:
      - "8080:8080"
    hostname: entry
    networks:
      - grades_app
    depends_on:
      - "entry_db"

  results_db:
    image: results_db
    restart: always
    ports:
      - "2717:27017"
    hostname: results_db
    networks:
      - grades_app

networks:
  grades_app:
    name: grades_app

