version: '3.3'

services:
  entry_db:
    build: ./entry_db
    restart: always
    #ports:
    #  - "3306:3306"
    hostname: entry_db
    networks:
      - grades_app
  
  entry:
    build: ./entry
    restart: always
    #ports:
    #  - "8080:8080"
    hostname: entry
    networks:
      - grades_app
    depends_on:
      - "entry_db"

  results_db:
    build: ./results_db
    restart: always
    #ports:
    #  - "2717:27017"
    hostname: results_db
    networks:
      - grades_app

  results:
    build: ./results
    restart: always
    #ports:
    #  - "8090:8090"
    hostname: results
    networks:
      - grades_app
    depends_on:
      - "results_db"

  analytics:
    image: analytics
    restart: always
    #ports:
    #  - "8100:8100"
    hostname: analytics
    networks:
      - grades_app
    depends_on:
      - "entry_db"
      - "results_db"

  authentication:
    build: ./authentication
    restart: always
    ports:
      - "80:80"
    networks:
      - grades_app
    depends_on:
      - "entry"
      - "results"

networks:
  grades_app:
    name: grades_app

